version: 2
    
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "04:05:5d:4f:4d:2b:93:f3:2b:e6:1e:3d:e5:c3:b3:e4"
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build pages
          command: bin/create_decks
      - run:
          name: Install gh-pages and configure git
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@farbenmeer.de"
            git config user.name "ci-build"
      - run:
          name: Deploy build to gh-pages branch
          command: gh-pages --dist build
    
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
